### ISSUE TITLE
Can't find "search.jira-issues.alfredworkflow"? 

### ISSUE THREAD

**Issue by jngnyc** [swissmanu/search-jira-issues-alfred-workflow#9]
Hello all,

I can't seem to find the `search.jira-issues.alfredworkflow` file anywhere in the repo to install.

Am I completely missing something? 

Thanks in advance all

**Comment by jessedobbelaere** [comment]
You can download the first release here on github, then install it in Alfred and then open it in Finder and replace the contents of that folder with the contents of the latest release (I read this on this github page...)

**Comment by jngnyc** [comment]
Ah, that worked for getting the workflow to install but now I'm running into a separate problem. To avoid clutter, I'll close this out as 'resolved' and open a new issue.

Thanks @jessedobbelaere!
